# Generated by Django 4.0.4 on 2022-05-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strongest_link_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='body',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
    ]
