# Generated by Django 4.0.4 on 2022-05-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongest_link_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/strongest-link/image/upload/v1651852463/lgo5em5rwqeuiduqza71.png', null=True),
        ),
    ]
