# Generated by Django 4.0.4 on 2022-05-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongest_link_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='attendees',
        ),
        migrations.AddField(
            model_name='location',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='strongest_link_app.userprofile'),
        ),
    ]
