# Generated by Django 4.0.4 on 2022-05-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongest_link_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='attendees',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
