# Generated by Django 4.0.4 on 2022-05-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongest_link_app', '0002_alter_cardio_user_alter_weightlifting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightlifting',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
