# Generated by Django 4.0.4 on 2022-05-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongest_link_app', '0003_location_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('Gym', 'Gym'), ('Run', 'Run'), ('Bike', 'Bike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.URLField(),
        ),
    ]
