# Generated by Django 4.0.4 on 2022-05-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongest_link_app', '0004_userprofile_about_me_userprofile_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('', 'Unspecified'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
